# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Liminal.Market smart contracts CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3      
      with:
        node-version: 16.15.0
        cache: 'npm'
    - run: npm ci
    - run: npm run compile
    - run: npm run test
    - run: npm run coverage
    - name: slither-action
      uses: crytic/slither-action@v0.1.1
    - name: slither-static-analysis
      uses: luisfontes19/slither-static-analysis-action@v0.3.4 
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOVUPLOADTOKEN }}
        file: '/coverage/coverage-final.json'

      
